services:
  client:
    image: network-rail-client
    build:
      context: ..
      dockerfile: docker/Dockerfile-client
    environment:
      - NTROD_USERNAME=${NTROD_USERNAME}
      - NTROD_PASSWORD=${NTROD_PASSWORD}
    entrypoint: ["uv", "run", "connect_and_subscribe.py"]
    networks:
      - monitoring

  ui:
    image: network-rail-ui
    build:
      context: ..
      dockerfile: docker/Dockerfile-ui-server
    entrypoint: [ "uv", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info" ]
    ports:
      - "8000:8000"
    networks:
      - monitoring

  nats:
    image: nats:2.12.1
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--http_port=8222"
      - "--name=nats-server"
    networks:
      - monitoring

  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    container_name: nats-exporter
    command:
      - "-varz"
      - "-connz"
      - "-subz"
      - "-routez"
      - "http://nats:8222"
    ports:
      - "7777:7777"
    depends_on:
      - nats
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ../prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - nats-exporter
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    volumes:
      - ../grafana-data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
