FROM python:3.13-slim

# handle UV
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

# handle Python deps
COPY pyproject.toml ./pyproject.toml
COPY uv.lock ./uv.lock
RUN uv sync

# handle business logic
COPY connect_and_subscribe.py ./connect_and_subscribe.py
